name: Run Cypress end-to-end tests
on:
  push:
    branches: [master, development]
  pull_request:
    branches: [master, development]

jobs:
  cypress-run:
    runs-on: ubuntu-16.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          # Run the application locally. This is needed to run the Cypress tests.
          start: npm start
          # quote the url to be safe against YML parsing surprises
          wait-on: 'http://localhost:3000'
